sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t melkfett/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true melkfett/react-test npm test

after_success:
  - docker build -t melkfett/multi-client ./client
  - docker build -t melkfett/multi-nginx ./nginx
  - docker build -t melkfett/multi-server ./server
  - docker build -t melkfett/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "melkfett" --password-stdin
  # Take those images and push them to docker hub
  - docker push melkfett/multi-client
  - docker push melkfett/multi-nginx
  - docker push melkfett/multi-server
  - docker push melkfett/multi-worker
